name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '.changeset/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-deep: 0

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install deps
        run: yarn install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          version: yarn ci:version
          publish: yarn ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
