name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '.changeset/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-deep: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: |
          npm install -g pnpm
          pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          publish: pnpm ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
